#!/bin/bash
function _msg { echo "$@" >&2; }
function _dbg { [[ $NODEJS_BUILD_DBG == 1 ]] && echo "$@" >&2; }

VERSION=1.3

OUT=""; PRE_CLEAN=""; POST_CLEAN=""; ARCH=""; APIL=""; STL=""; VERBOSE=""; FULL=""; FORCE=""; BRANCH="";

while [[ $# -gt 0 ]]; do
    _dbg "\"$1\""
    case $1 in
    --arch) case $2 in arm|arm64|x86|x64|mipsel) ARCH=$2; _dbg " ARCH=\"$2\""; shift;;
            ""|-*) _msg "expect arch behind $1. Must be arm(default)|arm64|x86|x64|mipsel"; exit 1;;
            *) _msg "invalid arch \"$2\". Must be arm(default)|arm64|x86|x64|mipsel"; exit 1;;
            esac
            ;;
    --api)  case $2 in min|max) APIL=$2; _dbg " APIL=\"$2\""; shift;;
            ""|-*) _msg "expect Android API level behind $1. Must be min(default)|max|an integer"; exit 1;;
            *[!0-9]*) _msg "invalid Android API level \"$2\". Must be min(default)|max|an integer"; exit 1;;
            *) APIL=$2; _dbg " APIL=\"$2\""; shift;;
            esac
            ;;
    --stl)  case $2 in gnustl|libc++|stlport) STL=$2; _dbg " STL=\"$2\""; shift;;
            ""|-*) _msg "expect C++ STL behind $1. Must be gnustl(default)|libc++|stlport"; exit 1;;
            *) _msg "invalid C++ STL \"$2\". Must be gnustl(default)|libc++|stlport"; exit 1;;
            esac
            ;;
    arm|arm64|x86|x64|mipsel)
            ARCH=$1; _dbg " ->ARCH"
            ;;
    -o|--out)  case $2 in
            ""|-*) _msg "expect output dir behind $1"; exit 1;;
            *) OUT=$2; _dbg " OUT=\"$2\""; shift;;
            esac
            ;;
    --pre-clean)
            PRE_CLEAN=$1; _dbg " ->PRE_CLEAN"
            ;;
    --post-clean)
            POST_CLEAN=$1; _dbg " ->POST_CLEAN"
            ;;
    --full)
            FULL=$1; _dbg " ->FULL"
            ;;
    --force)
            FORCE=$1; _dbg " ->FORCE"
            ;;
    -v|--verbose)
            VERBOSE=--verbose; _dbg " ->VERBOSE"
            ;;
    --help*|--version)
            break
            ;;
    --*)
            _msg "invalid long option \"$1\". Must be --out|--full|--force|--pre-clean|--post-clean|--arch|--api|--stl|--verbose|--version|--help"
            exit 1
            ;;
    -*)
            _msg "invalid short option \"$1\". Must be -o(out) or -v(verbose)"
            exit 1
            ;;
    "")
            _dbg " :skip isolated empty arg"
            ;;
    *)
            BRANCH=$1; _dbg " ->BRANCH"
    esac

    shift
done

case $1 in
--help)
    _msg "${0##*/} $VERSION"
    _msg "Build node.js for android from source in current dir"
    _msg ""
    _msg "Usage: ${0##*/} [OPTIONS] [branch]"
    _msg "--------------------------------------------------------------------------------"
    _msg "branch          git branch name. For example: v6.6.0, master"
    _msg "                This will use git to checkout the branch, then build for all "
    _msg "                arch (arm arm64 x86 x64 mipsel)."
    _msg "                The output will be saved at "
    _msg "                 ../nodejs-N.N.N-android-ARCH"
    _msg "                 ../nodejs-N.N.N-android-ARCH-full"
    _msg "                The ARCH means above arch. The N.N.N means branch(v striped)"
    _msg "                The .. maybe replaced by the DIR specified by -o,--out"
    _msg ""
    _msg "                Once branch is specified, only following options will be used:"
    _msg "                 -o --out --api --stl -v --verbose"
    _msg "OPTIONS:"
    _msg " -o DIR, --out DIR"
    _msg "                Output dir. By default is \$PWD-out"
    _msg " --force        Enable overwrite output dir if already exists"
    _msg " --full"
    _msg "                Full build, not specify any --without-... option to NodeJS,"
    _msg "                otherwise --without-snapshot --without-inspector --without-intl"
    _msg ""
    _msg " --pre-clean    Clean before build"
    _msg "                The cleaning is done by first try call (make clean),"
    _msg "                then (git clean -fdx && git reset --hard as possible)"
    _msg "                then (rm -fr out) as final resort"
    _msg " --post-clean   Clean on build success. The cleaning is same as --pre-clean"
    _msg ""
    _msg " [--arch] ARCH  Android architecture:"
    _msg "                {arm(default)|arm64|x86|x64|mipsel}"
    _msg " --api    APIL  Android API level:"
    _msg "                {min(default)|max|an integer}"
    _msg " --stl    STL   C++ STL to use:"
    _msg "                {gnustl(default)|libc++|stlport}"
    _msg ""
    _msg " -v, --verbose  Show verbose information, include compiler arguments"
    _msg " --version      Show version of this tool"
    exit 0
    ;;
--version)
    _msg $VERSION
    exit 0
    ;;
esac

[[ $VERBOSE ]] && export AGCC_VERBOSE=1

if [[ $BRANCH ]]; then
    VER=${BRANCH#v} #remove first char v

    _msg "clean && checkout $BRANCH"
    git clean -fdx && git reset --hard && git checkout "$BRANCH" || exit 1
    _msg ""
    _msg "------------------------------------------------------------------------"
    _msg current version of source of NodeJS:
    git log -1 --oneline --decorate
    _msg "------------------------------------------------------------------------"

    [[ ! $OUT ]] && OUT=..
    mkdir $OUT/logs 2>/dev/null

    [[ $APIL ]] && APIL="--api $APIL"
    [[ $STL ]] && STL="--stl $STL"

    results=()

    for arch in arm arm64 x86 x64 mipsel; do

        "$0" --arch $arch    -o $OUT/nodejs-$VER-android-$arch         $APIL $STL --pre-clean --post-clean         --force 2>&1 \
        | tee $OUT/logs/nodejs-$VER-android-$arch

        if [[ ${PIPESTATUS[0]} == 0 ]]; then
            results+=("SUCCESS: $OUT/nodejs-$VER-android-$arch")
        else
            results+=("FAILURE: $OUT/nodejs-$VER-android-$arch")
        fi

        "$0" --arch $arch    -o $OUT/nodejs-$VER-android-$arch-full    $APIL $STL --pre-clean --post-clean --full  --force 2>&1 \
        | tee $OUT/logs/nodejs-$VER-android-$arch-full

        if [[ ${PIPESTATUS[0]} == 0 ]]; then
            results+=("SUCCESS: $OUT/nodejs-$VER-android-$arch-full")
        else
            results+=("FAILURE: $OUT/nodejs-$VER-android-$arch-full")
        fi
    done

    _msg "--------------------------------------------------------------------------------"
    for r in "${results[@]}"; do
        _msg $r
    done
    _msg Done, please check $OUT/logs/ and $OUT/nodejs-$VER-android-\* to see result.
    exit 0
fi

[[ ! $OUT ]] && { OUT=$PWD-out || exit 1; }
if [[ ! -d $OUT ]]; then
    mkdir -pv "$OUT" || exit 1
else
    [[ ! $FORCE ]] && { _msg "auto chosen output dir already exists: \"$OUT\". To enable overwrite it, use --force"; exit 1; }
fi

[[ ! $ARCH ]] && ARCH=arm
[[ ! $APIL ]] && APIL=min
[[ ! $STL ]] && STL=gnustl

_msg "source dir: \"$PWD\"";
_msg "output dir: \"$OUT\"";


#pre-clean
[[ $PRE_CLEAN ]] && { [[ -f Makefile ]] && type -p make > /dev/null && make clean; [[ -d .git ]] && type -p git > /dev/null && { git clean -fdx; git reset --hard; }; rm -fr out node; }

if [[ $FULL ]]; then
    case $OSTYPE in
    darwin*)
        case $ARCH in
        arm    ) android-gcc-toolchain arm    $APIL $STL --host ar-dual-os,gcc-no-lrt,gcc-m32 -C <<< "./configure --dest-cpu=arm    --dest-os=android && make" ;;
        arm64  ) android-gcc-toolchain arm64  $APIL $STL --host ar-dual-os,gcc-no-lrt         -C <<< "./configure --dest-cpu=arm64  --dest-os=android && make" ;;
        x86    ) android-gcc-toolchain x86    $APIL $STL --host ar-dual-os,gcc-no-lrt,gcc-m32 -C <<< "sed -i.bak 's/cross_compiling = target_arch != host_arch/cross_compiling = True/' configure && ./configure --dest-cpu=x86 --dest-os=android && make" ;;
        x64    ) android-gcc-toolchain x64    $APIL $STL --host ar-dual-os,gcc-no-lrt         -C <<< "sed -i.bak 's/cross_compiling = target_arch != host_arch/cross_compiling = True/' configure && ./configure --dest-cpu=x64 --dest-os=android --openssl-no-asm && make" ;;
        mipsel ) android-gcc-toolchain mipsel $APIL $STL --host ar-dual-os,gcc-no-lrt,gcc-m32 -C <<< "./configure --dest-cpu=mipsel --dest-os=android && make" ;;
        esac;;
    linux*)
        case $ARCH in
        arm    ) android-gcc-toolchain arm    $APIL $STL --host gcc-lpthread,gcc-m32 -C <<< "./configure --dest-cpu=arm    --dest-os=android && make" ;;
        arm64  ) android-gcc-toolchain arm64  $APIL $STL --host gcc-lpthread         -C <<< "./configure --dest-cpu=arm64  --dest-os=android && make" ;;
        x86    ) android-gcc-toolchain x86    $APIL $STL --host gcc-lpthread,gcc-m32 -C <<< "sed -i.bak 's/cross_compiling = target_arch != host_arch/cross_compiling = True/' configure && ./configure --dest-cpu=x86 --dest-os=android && make" ;;
        x64    ) android-gcc-toolchain x64    $APIL $STL --host gcc-lpthread         -C <<< "sed -i.bak 's/cross_compiling = target_arch != host_arch/cross_compiling = True/' configure && ./configure --dest-cpu=x64 --dest-os=android --openssl-no-asm && make" ;;
        mipsel ) android-gcc-toolchain mipsel $APIL $STL --host gcc-lpthread,gcc-m32 -C <<< "./configure --dest-cpu=mipsel --dest-os=android && make" ;;
        esac;;
    *) _msg "unsupported host OS $OSTYPE. Please use Mac or Linux"; exit 1 ;;
    esac
else
    case $ARCH in
    arm    ) android-gcc-toolchain arm    $APIL $STL <<< "./configure --dest-cpu=arm    --dest-os=android --without-snapshot --without-inspector --without-intl && make" ;;
    arm64  ) android-gcc-toolchain arm64  $APIL $STL <<< "./configure --dest-cpu=arm64  --dest-os=android --without-snapshot --without-inspector --without-intl && make" ;;
    x86    ) android-gcc-toolchain x86    $APIL $STL <<< "./configure --dest-cpu=x86    --dest-os=android --without-snapshot --without-inspector --without-intl && make" ;;
    x64    ) android-gcc-toolchain x64    $APIL $STL <<< "./configure --dest-cpu=x64    --dest-os=android --without-snapshot --without-inspector --without-intl --openssl-no-asm && make" ;;
    mipsel ) android-gcc-toolchain mipsel $APIL $STL <<< "./configure --dest-cpu=mipsel --dest-os=android --without-snapshot --without-inspector --without-intl && make" ;;
    esac
fi

[[ $? != 0 ]] && exit 1

rm -fr "$OUT/"*

#copy build result to $OUT/{bin,lib,include}
android-gcc-toolchain $ARCH $APIL $STL -C make DESTDIR="$OUT" PREFIX="" install | grep -vE '^installing|^symlinking|^removing'
[[ ${PIPESTATUS[0]} != 0 ]] && { _msg "failed to run make install"; exit 1; }

mkdir "$OUT/extras" && \
for f in out/Release/*; do
    [[ -f $f && -x $f && ${f##*/} != node ]] && ln -f "$f" "$OUT/extras"
done

ls -lF "$OUT/bin/"* "$OUT/extras/"*

#post-clean
[[ $POST_CLEAN ]] && { [[ -f Makefile ]] && type -p make > /dev/null && make clean; [[ -d .git ]] && type -p git > /dev/null && { git clean -fdx; git reset --hard; }; rm -fr out node; }
